* Competitive / Casual Game Modes Design Doc
    This path could be dynamically set, the way it is in Dokapon, but the reason I shy away from this approach is because in my experience with Dokapon... none of our groups were interested in playing any of these modes. they somehow felt less real than the "main" story mode. I want to make sure that there is a clear distinction, showing that there are three ways to play the game: Story, Casual, and Competitive. Story is detailed elsewhere, but here we want to to talk about Competitive and Casual. Looking to the world of e-sports, there are typically only one or two "modes" that are competitive, while casual has more free reign to do seasonal content, and custom games. In that spririt I want to find a formula of sorts that provides a version of the game with a set number of players, and curates the experience at different player numbers to be competitively balanced, and feel like victories are earned, and that there is always more to learn--a path to further success. Now part of that is hard because it is'nt a reflex based game... but I want to allow for the game to not feel "stale"
** Competitive
**** Ideas
     Some starting thoughts on this: What if we took a template from other competitive games and tried to apply it to a party game format? maybe you have two teams of 2, and each has to defeat a "goalie" of the boss at the enemy's castle, like taking a nexus, and there could be different character build strategies for getting to the goal. Or there could be a battle royale influence, where you start with 6 to 8 players, starting at different locations, converging on one objective, and winner takes all, with permadeath put into place. With this, you could even make the games very fast, say 10 minutes, with async turns (out of combat) and do a "first to 3" kind of deal", where you only come back to life if no one got the goal the round where you died? As a third option, autobattlers are most similar in mechanics to the part game, out of the competitive games I've mentioned so far, so maybe every square you go to is a town, where you can build semi-random armies, that attack opponent armies, also semi-randomly, upgrading your armies as you go, and last man standing wins. Or it could stay more in line with the modes of Dokapon, which were: first to # of kills, # of towns, net worth, or net worth at the end of a turn limit. 
** Casual
*** first to....
